branch-defaults:
  master:
    environment: Ebhostingafullstackapplication-env-1
deploy:
  artifact: www/Archive.zip
global:
  application_name: EB-Hosting-a-Full-Stack-Application
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  sc: git
